version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/base:2024.01
  playwright-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.37.0-focal

jobs:
  wait-job:
    executor: default-executor
    steps:
      - run:
          name: Wait for 30 seconds
          command: sleep 30

  hello-world-job:
    executor: default-executor
    steps:
      - run:
          name: Echo Hello World
          command: echo "Hello World"

  playwright-tests:
    executor: playwright-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Playwright tests
          command: npx playwright test

workflows:
  version: 2
  conditional-workflow:
    jobs:
      - wait-job
      - hello-world-job:
          requires:
            - wait-job: canceled
      - playwright-tests:
          requires:
            - hello-world-job
