version: 2.1

executors:
  qt-executor:
    docker:
      - image: cimg/base:current
    working_directory: ~/project

jobs:
  build:
    executor: qt-executor
    steps:
      - checkout
      - run:
          name: Update ubuntu
          command: sudo apt-get update
      - run:
          name: Install Qt
          command: |
            sudo apt-get install -y qt6-base-dev
            wget https://download.qt.io/official_releases/qt/6.2/6.2.4/single/qt-everywhere-src-6.2.4.tar.xz
            tar xf qt-everywhere-src-6.2.4.tar.xz
            cd qt-everywhere-src-6.2.4
            ./configure -opensource -confirm-license -nomake tests -nomake examples
            make -j$(nproc)
            sudo make install
      - run:
          name: Where Am I
          command: |
            pwd
            ls -l
            lscpu
      - run:
          name: Versions
          command: g++ --version
      - run:
          name: Configure CMake
          command: |
            cd src
            cmake -B $PWD/src/build -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      - run:
          name: Build
          command: |
            cd src
            cmake --build $PWD/src/build --config ${BUILD_TYPE} --target seergdb --parallel $(nproc)
      - run:
          name: Tar
          command: |
            cd src/build
            cp ../../LICENSE .
            cp ../../CHANGELOG.md .
            tar zcvf seergdb.tar.gz LICENSE CHANGELOG.md seergdb
      - run:
          name: List Results
          command: |
            cd src
            ls -l build/

workflows:
  build_and_release:
    jobs:
      - build
