version: 2.1

executors:
  qt-executor:
    docker:
      - image: cimg/base:current
    working_directory: ~/project

jobs:
  build:
    executor: qt-executor
    steps:
      - checkout
      - run:
          name: Update ubuntu
          command: sudo apt-get update
      - run:
          name: Install Qt5
          command: sudo apt-get install -y qtbase5-dev libqt5charts5-dev libqt5printsupport5
      - run:
          name: Set Qt5 Environment
          command: echo 'export CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5' >> $BASH_ENV
      - run:
          name: Where Am I
          command: |
            pwd
            ls -l
            lscpu
      - run:
          name: Versions
          command: g++ --version
      - run:
          name: Configure CMake
          command: |
            cd src
            cmake -B $PWD/src/build -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5 -DQTVERSION=QT5
      - run:
          name: Echo Qt Version
          command: |
            cd src
            cmake --build $PWD/src/build --target help | grep "Compile with QT"
      - run:
          name: Build
          command: |
            cd src
            cmake --build $PWD/src/build --config ${BUILD_TYPE} --target seergdb --parallel $(nproc)
      - run:
          name: Tar
          command: |
            cd src/build
            cp ../../LICENSE .
            cp ../../CHANGELOG.md .
            tar zcvf seergdb.tar.gz LICENSE CHANGELOG.md seergdb
      - run:
          name: List Results
          command: |
            cd src
            ls -l build/

workflows:
  build_and_release:
    jobs:
      - build
